language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: dwhaRkN6Kv4FteunPx9lZ+ccxM7S/R880n8XKAfLF/Fu3pC5+zl41cg/xvWuRQNj3woP5VvsuvU7EVw5kf53xDchWt3quf9WTQ77ccS9WoEdxKaZHijGXAK5w4kkjQIMMAcQFYhxKzfTqSCuBsp7tDnN9mTZ8jyy8qKk6FkPnckgvK5A+KmPmFDXf5jrGRfYPvsj7zvP4XQolV1tsnj6ePp8s8viHFYCYCvoo8X2/68E966mJoYo0t7cLbGNIKU1mOx5MPwfvV+uxlgiBp1IegvQlijWsjAh1baOrPy5rOQ5O4+Zk8lONEx6K4vjrIFexeFWjUBj+IEhRwjpbZ5M66US9u8l8Ig/Z5ZWurv2ymJPPbMXNaMjFZO/HyW8mHUaWvuRA8KrbNKblhjdOXSINpnrDumkvnlnAm8lQ30wA702hkzJk17w3ElpyWLPhw/h1g1PeStuisdd1h4RCGKHsAMaE2yJf5Ebp4rhZe80CRedWtLaOyw717lPTMt0NyZW8Gq2fRr4aMlzEKM8f9BXX0UeEjLmIK2Wvz0OEz5ZBs0BPAGSCISI2iMVqL5AIyZg5OcS4PGWZ8Ip+v+AuDPtmg/1eGHgjduXKezrQ2OiXHlcroWvoD86TCALGEITHN9u4u6cvzUF/BPEvugymdiFc7eLlKoTL+3HBP6uULQHq4U=
  app: blog-app-mongoose-challenge-solution
  on:
    repo: sgarcia-dev/blog-app-mongoose-challenge-solution
