language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: ZRcSa6FEM1dZLgCnW0E/sSf2k+CihcqFVKB5YPbT79cdLntYS4SS2NkinreTutl9RtjE2LYSi+rOMQLn2bWABksBjpUwG1rS3eiPNhgCH8iNZtpCrEkpDwEgm1CNUHtlSEoMYkLzG9Xf+4UqWcLS4yB9Z5l+lCj7OLwMZ+3gNJnkkxDCZ2viYnKKlHHNWPSTaLGZi4KrUOQd/u8zflPZfGs9b10142ZXTKVpqapBI1hQLe2jcjJwQ/vxQb3tS+jxbYDAlzeXObcQoDSAThEVb/tAB1NX7VIOm4InE2T6wqXjN7XHI0y+2N2M2AEzvbvGyu1WP0il/EuKCUUn+vXl7BzspNkQ2uH3Zv+CFcjdninjYQaGYDhwsFMQReJ4E8oxLALxo/qF6M3Dtm0q5F2iiRlkLADRTFuWVkYuljytjnvCpcvTLMwX9cfbi7aKs94IevGz60Cra1xPLlpF9syoYBd6+dZUwxYb15y7tzr89i8Ml3wFUuyFOC8F4c6576Pga+9ySNMB5LRMqf4uF0/KALSALSef97eLx03jqcSHP0P/3Mt6cyzRKApXoj6+9bN8jRKxXMCVHEuswabXVbMGszJxVlrDJ/jr8VrMQXV2fXPqf+dIjNZseDRszOPdVVV6COTPtZJzA2S6lkQJYvcYuog7Q9/gyH2I2COXrKkQklw=
  app: blog-app-mongoose-challenge-solution
  on:
    repo: sgarcia-dev/blog-app-mongoose-challenge-solution
